### ISSUE TITLE
"User templates" with higher priority

### ISSUE THREAD

**Issue by henriquebaron** [tibabit/vim-templates#11]
It would be nice if the plugin had a different prioritization system so that users can override the templates that are shipped with the plugin.

_For example_, I wrote a template `~/.vim/templates/html.template` according to my preferences but, instead of that, the template stored at `~/.vim/plugged/vim-templates/templates/html.template` is loaded.

I know I can make a template with the same name as the file (for instance, something like `index.html`) but I think that searching templates _first_ in the user directories and then in the plugin directory would already solve it.

**Comment by tibabit** [comment]
There are few other ways to accomplish this. Look at this [documentation](https://github.com/tibabit/vim-templates#search-paths).
