### ISSUE TITLE
Error loading templates

### ISSUE THREAD

**Issue by MahbubAlam231** [tibabit/vim-templates#4]
I have few errors while loading templates. I don't know how to resolve them.
![vim_templates](https://user-images.githubusercontent.com/37048605/38777752-11fb528c-40cb-11e8-9f56-c8369ad6364b.jpg)

**Comment by HustLion** [comment]
Please try the newest code.

**Comment by tibabit** [comment]
Since, there has been no further queries on this, I am assuming it has been resolved.
Reopen it, if required.
