### ISSUE TITLE
Is it possible to use a custom template by default?

### ISSUE THREAD

**Issue by Davey-Hughes** [tibabit/vim-templates#5]
Is it possibly to specify, per filetype, which template file in particular to use? I can add the path just fine, and manually insert a template with the functions, but on a new file I'd like to define my own templates to use by default.

If this isn't already added, might I suggest a key-value pair list? Such as:
let g:template_defaults = [
    \ 'c': '\~/path/cmain.template,
    \ 'py': '\~/path/pymain.template
\]

**Comment by tibabit** [comment]
Templates are searched on per file basis so if you put your default templates in, let's say, ~/templates directory, then these templates will be used for all the extensions that are present in this directory, for the rest of the templates default path will be used.
